# Generated by Django 3.2.8 on 2022-03-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Used_Car_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Company', models.CharField(max_length=30, null=True)),
                ('Car_name', models.CharField(max_length=30, null=True)),
                ('Car_Model', models.CharField(max_length=20, null=True)),
                ('Car_Year', models.IntegerField(null=True)),
                ('Car_KM', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_1.car_company')),
            ],
        ),
    ]
