# Generated by Django 3.2.8 on 2022-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0003_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_car_details',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='used_car_details',
            name='reg_no',
            field=models.IntegerField(null=True),
        ),
    ]
