# Generated by Django 3.2.8 on 2022-03-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0004_auto_20220307_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_car_details',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_1.user_info'),
        ),
    ]
