# Generated by Django 3.2.8 on 2022-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0005_alter_used_car_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_car_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
