# Generated by Django 3.2.8 on 2022-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0007_alter_used_car_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_car_details',
            name='Mobile_No',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
