# Generated by Django 3.2.8 on 2022-03-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0008_used_car_details_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.CharField(max_length=50, null=True)),
                ('engine', models.CharField(max_length=50, null=True)),
                ('powertorque', models.CharField(max_length=50, null=True)),
                ('gearbox', models.CharField(max_length=50, null=True)),
                ('fueleconomy', models.CharField(max_length=50, null=True)),
                ('wheelbase', models.CharField(max_length=50, null=True)),
                ('infoitainment', models.CharField(max_length=50, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_1.car_info')),
            ],
        ),
    ]
