# Generated by Django 3.2.8 on 2022-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0009_car_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car_details',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
