# Generated by Django 3.2.8 on 2022-03-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0010_auto_20220327_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggest_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('Price', models.CharField(max_length=50, null=True)),
                ('Rating', models.CharField(max_length=50, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pro1', models.CharField(max_length=50, null=True)),
                ('pro2', models.CharField(max_length=50, null=True)),
                ('pro3', models.CharField(max_length=50, null=True)),
                ('con1', models.CharField(max_length=50, null=True)),
                ('con2', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
