# Generated by Django 3.2.8 on 2022-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0011_suggest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest_details',
            name='Price_Range',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
