# Generated by Django 3.2.8 on 2022-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0012_suggest_details_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest_details',
            name='car_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
