# Generated by Django 3.2.8 on 2022-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0015_used_car_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_car_details',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
