# Generated by Django 3.2.8 on 2022-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_1', '0016_used_car_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_car_details',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
